### ISSUE TITLE
I can't upload work to the repository

### ISSUE THREAD

**Issue by Seeryoga** [theedanico2/Student#1]
Should I upload work to this repository, or create my own? 
[Savchenko_1.zip](https://github.com/theedanico2/Student/files/14343817/Savchenko_1.zip)

**Comment by theedanico2** [comment]
did you clone the repository?

**Comment by theedanico2** [comment]
for you to upload, i have to add you as a collaborator.

**Comment by nidedno** [comment]
@theedanico2 hi! I too can't upload my work. Can you add me to collab?

**Comment by theedanico2** [comment]
done
