### ISSUE TITLE
Explane lab 4

### ISSUE THREAD

**Issue by nidedno** [theedanico2/Student#21]
@theedanico2 Hi! We have question about lab4 about moment when we need to actualize url's from there https://mockapi.io/
We just need to upload «Приложение для учета финансов» and that's all?

**Comment by nidedno** [comment]
Can you also send us a test#1 ?

**Comment by theedanico2** [comment]
Lab 4: Update. Optimize the app by adding some additional features / redesigning the app, etc. 

Test: Check your email. You should receive an email from Extended Forms.
